### ISSUE TITLE
运行python run.py deploy之后，出现下面的情况，不知道哪里差了

### ISSUE THREAD

**Issue by kentcc88** [abbeyokgo/payjs_faka#3]
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from app import app, db, login_manager
  File "/root/payjs_faka/faka/app/__init__.py", line 5, in <module>
    from flask_bootstrap import Bootstrap
ImportError: No module named flask_bootstrap

**Comment by zhuweiyou** [comment]
同

**Comment by abbeyokgo** [comment]
pip install flask_bootstrap
